spring:
  application:
    name: userMS

  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
#    url: "jdbc:mysql://localhost:3306/user_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC"
    url: ${MYSQL_URL}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8080

bookMS:
  url: ${BOOK_MS_URL}